### ISSUE TITLE
Undefined method unpipe

### ISSUE THREAD

**Issue by hason** [finnp/gitter-irc-bot#13]
```
/var/gitter-irc-bot-symfony/index.js:48
             chatStream.unpipe()
                        ^
TypeError: Object #<Request> has no method 'unpipe'
      at Request.gitterAttach (/.../gitter-irc-bot/index.js:48:24)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/.../gitter-irc-bot/node_modules/request/request.js:996:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:929:16
      at process._tickCallback (node.js:419:13)
{ [Error: connect ECONNREFUSED]
   code: 'ECONNREFUSED',
   errno: 'ECONNREFUSED',
   syscall: 'connect' }
```

**Comment by finnp** [comment]
What version of node are you using?

**Comment by hason** [comment]
```
nodejs --version
v0.10.29
```

**Comment by finnp** [comment]
The problem was that request doesn't return a stream, but implements it's own `pipe` method. I now removed the `unpipe`, so this shouldn't happen again. Plese update to 1.2.1
