### ISSUE TITLE
`TypeError: Object #<Request> has no method 'unpipe'`

### ISSUE THREAD

**Issue by vinipsmaker** [finnp/gitter-irc-bot#14]
Some of the debug messages appear because I use `{"ircOpts": {"debug": true}}`. These are all the logs I have, but let me know if you need some info not related to logs (config...), then I can provide them.

    gitter: (engreimor) então 50 graus seria 50% quente e 100º seria 100% quente
    2 Jul 15:53:02 - SEND: PRIVMSG #ccppbrasil :(engreimor) então 50 graus seria 50% quente e 100º seria 100% quente
    Reattaching to gitter chat stream...
    /var/lib/openshift/558eb7db4382ece1a400010a/app-root/runtime/repo/node_modules/gitter-irc-bot/index.js:48
                chatStream.unpipe()
                           ^
    TypeError: Object #<Request> has no method 'unpipe'
        at Request.gitterAttach (/var/lib/openshift/558eb7db4382ece1a400010a/app-root/runtime/repo/node_modules/gitter-irc-bot/index.js:48:24)
        at Request.EventEmitter.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/var/lib/openshift/558eb7db4382ece1a400010a/app-root/runtime/repo/node_modules/gitter-irc-bot/node_modules/request/reques
    t.js:996:12)
        at IncomingMessage.EventEmitter.emit (events.js:117:20)
        at _stream_readable.js:920:16
        at process._tickDomainCallback (node.js:459:13)
    DEBUG: Program node server.js exited with code 8
    DEBUG: Starting child process with 'node server.js'

**Comment by finnp** [comment]
This should be fixed in 1.2.1. Please update the bot and let me know in case you are still having problems. :)
