### ISSUE TITLE
Gitter API changed, bot no longer works

### ISSUE THREAD

**Issue by rkitover** [finnp/gitter-irc-bot#31]
Getting this in my logs:

```
Connecting to IRC..
Connected to IRC, joined #vba-m
/usr/local/share/.config/yarn/global/node_modules/gitter-irc-bot/index.js:44
        var gitterName = json[0].username
                                 ^

TypeError: Cannot read property 'username' of undefined
    at Request._callback (/usr/local/share/.config/yarn/global/node_modules/gitter-irc-bot/index.js:44:34)
    at Request.self.callback (/usr/local/share/.config/yarn/global/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by nemesisdesign** [comment]
Having the same issue :-(

**Comment by nemesisdesign** [comment]
@rkitover In my case it doesn't seem like the API changed its contents, but my token is not valid anymore and I can't find a way to obtain a valid token that works.

I sent a PR that at least can help admins get notified about this issue in #32.

**Comment by nemesisdesign** [comment]
I rectify: I logged into gitter and got the new API token, which works correctly, I just forgot to reload `supervisor.d`, which was not loading the new token and hence kept on getting the unauthorized error message. After reloading the process with the new token the bridge started working again.

**Comment by rkitover** [comment]
I switched to gogitterirc, it's working more reliably because it doesn't use the API.

**Comment by wikimatze** [comment]
@nemesisdesign I have the same issues ... try your fix by getting a new token.

**Comment by feross** [comment]
Looks like Gitter changed the API token. Updating that in my code worked for me. This package should handle this error better by checking if `json.error` is set as this PR does: https://github.com/finnp/gitter-irc-bot/pull/32/files

**Comment by finnp** [comment]
I merged and published the PR that adds the better error handling.

**Comment by nemesifier** [comment]
:+1:
